version: "3.9"

services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: Postgres-bot
    environment:
      - POSTGRES_USER=${POSTGRES_USR}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: PgAdmin-bot
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PWD}
    ports:
      - "443:443"
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana:latest
    container_name: Grafana-bot
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USR}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PWD}
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: Redis-bot
    ports:
      - "6379:6379"
    command: >
      redis-server --requirepass ${REDIS_PWD}
